### ISSUE TITLE
Improve function signature readability

### ISSUE THREAD

**Issue by joeltine** [jleyba/js-dossier#72]
Currently, the format of a collapsed function signature is `<GENERICS> <FN_NAME>(<ARGS>)` (e.g., see http://google.github.io/closure-library/api/goog.array.html) . I think the readability of these could be improved by providing a more typical function signature format of `<RETURN_TYPE> <FN_NAME><GENERICS>(<TYPE> arg1, <TYPE> arg2....)`.

Alternatively (or in addition to), having the function cards expanded by default could help. The card contains the all the type information, including the return type.

**Comment by jleyba** [comment]
I've omitted types from the signature line because things can get really verbose, really quickly. Consider `goog.events.EventTarget#getListener`:

http://google.github.io/closure-library/api/goog.events.EventTarget.html#getListener

```
goog.events.ListenableKey getListener(/** (string|!goog.events.EventId<EVENTOBJ>) */ type, /** function(this: SCOPE, EVENTOBJ): (boolean|PredicateFunctionType) */ listener, /** boolean */ capture, /** SCOPE= */ opt_listenerScope)
```

At least including the return type might be worthwhile:

```
getListener(type, listener, capture, opt_listenerScope) ⇒ goog.events.ListenableKey
```

I'll have to think about how to handle generics in the method signature - they definitely hurt readability for goog.array
