### ISSUE TITLE
Direct user attention to search bar in new API

### ISSUE THREAD

**Issue by joeltine** [jleyba/js-dossier#73]
Per feedback in  https://groups.google.com/forum/#!topic/closure-library-discuss/lRtUBzLTgy8 , it's not always obvious the search bar is now the new entry point to search the API docs. Perhaps we can do something to draw user attention to the search bar? 

Some ideas:

- Add some "Start here" (or similar text) to the search box place holder text
- Mention "use search bar above" in the landing page text
- "Highlight" the search bar on the landing page

**Comment by jleyba** [comment]
Yup, UX definitely needs some love (help is appreciated!)

Some hidden shortcuts (they're at least listed on the element titles):

* The search bar is listed first in tab order
* <kbd>/</kbd> or <kbd>CTRL</kbd>+<kbd>E</kbd> will focus the search bar (E instead of F to avoid conflicting with browser's text find)
* <kbd>n</kbd> opens the side nav menu

**Comment by jleyba** [comment]
My current thinking is to make the nav menu always open on larger screens. Will try to work on it ~soon

**Comment by joeltine** [comment]
That sounds great. I've also udpated our readme.md with some pointer text.
